### ISSUE TITLE
Add numeric ID generation

### ISSUE THREAD

**Issue by thismaker** [ocluse/liquidsnow-cryptography#1]

**Comment by thismaker** [comment]
@Phystro  do you think you can try this one out. It is rather simple, all you need to do is add `IdKind.Numeric` and use the inbuilt `CryptoUtility.Random` method to generate a number.
for example, to generate a 5 digit number, you'd do this:
```cs
CryptoUtility.Random(10000, 99999).ToString(CultureInfo.InvariantCulture)
```
So now the trick is in determining the min and max values based on the input `length`

**Comment by PhyTensor** [comment]
OK. Trying it out

**Comment by thismaker** [comment]
Once you do open a PR and tag me I check it out.... Open a PR to the dev branch not main
